require "simhilarity/bits"
require "simhilarity/bk"
require "simhilarity/caching"
require "simhilarity/candidate"
require "simhilarity/candidates"
require "simhilarity/element"
require "simhilarity/score"
require "simhilarity/version"

require "simhilarity/matcher"
